name: whatthestudentsthink
version: 1.0.0
synopsis: "The backend for a website displaying charts of the 2017 National Student Survey."
maintainer: 5-o
license: GPL-3

dependencies:
  - base
  - containers
  - text
  - aeson
  - bytestring
  - scotty
  - megaparsec
  - scotty-tls
  - http-types

executables:
  server:
    main: Server.hs
    ghc-options: -Wall -O2 -threaded -main-is Server
    source-dirs:
      - haskellSrc
  redirect:
    main: Redirect.hs
    ghc-options: -Wall -O2 -threaded -main-is Redirect
    source-dirs:
      - haskellSrc
  generateCodes:
    main: GenerateCodes.hs
    ghc-options: -Wall -O2 -threaded -main-is GenerateCodes
    source-dirs:
      - haskellSrc
